"""empty message

Revision ID: 04acddd488fe
Revises: 00eaf024c5d6
Create Date: 2025-02-20 11:36:35.306033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04acddd488fe'
down_revision = '00eaf024c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_constraint('favorites_planets_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['name'], ['id'])
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_planets_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
